### PR TITLE
Add the method to create network hlfv1 and add memeber Peeradmin

### PR DESCRIPTION
**Pull request by LordwithGlory**
As the issues I asked [The network hlfv1 not exist](https://github.com/IBM/hyperledger-fabric-on-linux-one/issues/25), I find the way to solve it —— execute the shell "createPeerAdminCard.sh" and "startFabric.sh"in the folder "fabric-tools".

### CODE REVIEW

**Comment by farha777** [comment]
I found below error while running the command.

linux1@djblockchain:~/fabric-tools> ./createPeerAdminCard.sh
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
**FABRIC_VERSION is set to 'hlfv11'**
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

Cannot use v0.17.4 version of composer with fabric 1.1, v0.19 or higher is required
linux1@djblockchain:~/fabric-tools>

**Comment by LordwithGlory** [comment]
Maybe  you should update the version of Docker-Composer

**Comment by erikvaningen** [comment]
I have exactly the same problem:
> linux1@djblockchain:~/fabric-tools> ./createPeerAdminCard.sh
> Development only script for Hyperledger Fabric control
> Running 'createPeerAdminCard.sh'
> FABRIC_VERSION is set to 'hlfv11'
> FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
> 
> Cannot use v0.17.4 version of composer with fabric 1.1, v0.19 or higher is required
> linux1@djblockchain:~/fabric-tools>
> 

This configuration problem comes out of the box of this script:
https://raw.githubusercontent.com/IBM/HyperledgerFabric-on-LinuxOne/master/Linux1BlockchainScript.sh

Would you advise me to manually upgrade composer to version v0.19? Or any other advise?

**Comment by erikvaningen** [comment]
Awaiting any suggestion, I created my own version of
https://raw.githubusercontent.com/IBM/HyperledgerFabric-on-LinuxOne/master/Linux1BlockchainScript.sh
replacing all versions of composer  v0.17.4 with v0.19.4. 

After execustion I got indeed a playground with PeerAdmin@hlfv1
!

**Comment by erikvaningen** [comment]
Additional comment: While deploying a new network to hlv1, I got this error:

> An error has occurred
> Error: Error trying login and get user Context. TypeError: this.wallet.contains is not a function

This can be resolved by completely removing all the docker images and the .composer directory. Subsequently run the script Linux1BlockchainScript.sh again (changing 0.17.4 with 0.19.4).

**Comment by farha777** [comment]
@erikvaningen thanks alot  for your reply and support. I am in mid of deploying and Yes "Connection: hlfv1" is visible now in HL Portal....Will provide you feedback regarding my end results.

**Comment by farha777** [comment]
My Network is working..Thanks

**Pull request merged**
